FROM alpine AS builder
ARG REPONAME=Sample-Html-Css-Website
ENV REPONAME=$REPONAME

RUN apk update && \
	apk add git && \
	apk add wget && \
	apk add sed;

RUN wget vedant-mhatre.github.io/docker-nginx-configfile/nginx.conf && \
	sed -i "s/Sample-Html-Css-Website/${REPONAME}/" nginx.conf


RUN	git clone https://github.com/Vedant-Mhatre/${REPONAME}.git

RUN

FROM alpine
COPY --from=builder . .


RUN apk add nginx

RUN	adduser -D -g 'www' www && \
	mkdir /www && \
	chown -R www:www /var/lib/nginx && \
	chown -R www:www /www && \
	mkdir -p /run/nginx && \
	mv nginx.conf /etc/nginx/nginx.conf


CMD ["nginx"]
