FROM alpine
RUN apk update

RUN apk add nginx

RUN adduser -D -g 'www' www

RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

RUN apk add git
RUN cd /www/ ;git clone https://github.com/Vedant-Mhatre/Sample-Html-Css-Website.git


RUN mv /www/Sample-Html-Css-Website/nginx.conf  etc/nginx/nginx.conf


# /etc/init.d/nginx start
