FROM alpine

ENV REPONAME Sample-Html-Css-Website

RUN apk update && \
	apk add nginx && \
	apk add git && \
	apk add wget && \
	apk add sed;

RUN	adduser -D -g 'www' www && \
	mkdir /www && \
	chown -R www:www /var/lib/nginx && \
	chown -R www:www /www && \
	mkdir -p /run/nginx && \
	wget vedant-mhatre.github.io/docker-nginx-configfile/nginx.conf && \
	mv nginx.conf /etc/nginx/nginx.conf

CMD	cd /www/ && \
	git clone https://github.com/Vedant-Mhatre/${REPONAME}.git && \
	sed -i "s/Sample-Html-Css-Website/${REPONAME}/" /etc/nginx/nginx.conf && \
	echo SUCCESSFULLY-DEPLOYED  && \
	nginx
