FROM alpine

RUN	apk update && \
			apk add nginx && \
			apk add git;

RUN	adduser -D -g 'www' www && \
			mkdir /www && \
			chown -R www:www /var/lib/nginx && \
			chown -R www:www /www && \
			mkdir -p /run/nginx;

RUN	cd /www/ && \
			git clone https://github.com/Vedant-Mhatre/Sample-Html-Css-Website.git

RUN	mv /www/Sample-Html-Css-Website/nginx.conf  /etc/nginx/nginx.conf

CMD ["nginx"]

RUN ls
